#!/bin/bash
#
# DOT-CLAUDE Install Script
# Installs or merges DOT-CLAUDE configuration into user's ~/.claude/ or project .claude/
#
# Usage:
#   ./install.sh              # Interactive mode
#   ./install.sh --global     # Install to ~/.claude/
#   ./install.sh --project    # Install to ./.claude/
#   ./install.sh --merge      # Merge with existing config
#   ./install.sh --help       # Show help

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Get script directory (DOT-CLAUDE root)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOT_CLAUDE_ROOT="$(dirname "$SCRIPT_DIR")"

# Directories to sync
SYNC_DIRS=("commands" "skills" "rules" "modules" "scripts" "config" "hooks" "templates")

# Files to sync
SYNC_FILES=("settings.json")

print_banner() {
    echo -e "${CYAN}"
    echo "╔═══════════════════════════════════════════════════════════════╗"
    echo "║                                                               ║"
    echo "║     ██████╗  ██████╗ ████████╗       ██████╗██╗      ██╗     ║"
    echo "║     ██╔══██╗██╔═══██╗╚══██╔══╝      ██╔════╝██║     ██╔╝     ║"
    echo "║     ██║  ██║██║   ██║   ██║   █████╗██║     ██║    ██╔╝      ║"
    echo "║     ██║  ██║██║   ██║   ██║   ╚════╝██║     ██║   ██╔╝       ║"
    echo "║     ██████╔╝╚██████╔╝   ██║         ╚██████╗███████╔╝        ║"
    echo "║     ╚═════╝  ╚═════╝    ╚═╝          ╚═════╝╚══════╝         ║"
    echo "║                                                               ║"
    echo "║           Autonomous Claude Configuration System              ║"
    echo "╚═══════════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
}

print_help() {
    echo "DOT-CLAUDE Installation Script"
    echo ""
    echo "Usage: $0 [OPTIONS]"
    echo ""
    echo "Options:"
    echo "  --global       Install to ~/.claude/ (global configuration)"
    echo "  --project      Install to ./.claude/ (current project)"
    echo "  --merge        Merge with existing configuration (preserves custom)"
    echo "  --backup       Create backup before installing"
    echo "  --dry-run      Show what would be done without doing it"
    echo "  --force        Overwrite without confirmation"
    echo "  --agents       Install agent personality modules"
    echo "  --minimal      Install minimal bootstrap only"
    echo "  --help         Show this help"
    echo ""
    echo "Examples:"
    echo "  $0 --global --backup          # Fresh install to ~/.claude/ with backup"
    echo "  $0 --project --merge          # Merge into project .claude/"
    echo "  $0 --global --agents          # Install with full agent personality system"
}

backup_directory() {
    local target="$1"
    local backup_dir="${target}.backup.$(date +%Y%m%d_%H%M%S)"

    if [[ -d "$target" ]]; then
        echo -e "${YELLOW}Creating backup: $backup_dir${NC}"
        cp -r "$target" "$backup_dir"
        echo -e "${GREEN}✓ Backup created${NC}"
    fi
}

sync_directory() {
    local src="$1"
    local dest="$2"
    local merge="$3"

    if [[ ! -d "$src" ]]; then
        return
    fi

    echo -e "${BLUE}Syncing: $src -> $dest${NC}"

    if [[ "$merge" == "true" && -d "$dest" ]]; then
        # Merge mode: copy new files, don't overwrite existing
        rsync -av --ignore-existing "$src/" "$dest/"
    else
        # Fresh install: copy everything
        mkdir -p "$dest"
        rsync -av "$src/" "$dest/"
    fi
}

sync_file() {
    local src="$1"
    local dest="$2"
    local merge="$3"

    if [[ ! -f "$src" ]]; then
        return
    fi

    if [[ "$merge" == "true" && -f "$dest" ]]; then
        echo -e "${YELLOW}Skipping existing: $dest${NC}"
        return
    fi

    echo -e "${BLUE}Copying: $src -> $dest${NC}"
    cp "$src" "$dest"
}

generate_claude_md() {
    local target="$1"
    local mode="$2"  # "global" or "project"

    local claude_md="$target/CLAUDE.md"

    if [[ -f "$claude_md" && "$MERGE_MODE" == "true" ]]; then
        echo -e "${YELLOW}Merging with existing CLAUDE.md${NC}"

        # Create merged version
        local temp_file=$(mktemp)

        cat > "$temp_file" << 'HEADER'
# Claude Configuration

<!-- This file was generated by DOT-CLAUDE install script -->
<!-- Original content preserved below, DOT-CLAUDE additions follow -->

HEADER

        # Add existing content
        echo "<!-- === ORIGINAL CONTENT === -->" >> "$temp_file"
        cat "$claude_md" >> "$temp_file"
        echo "" >> "$temp_file"
        echo "<!-- === DOT-CLAUDE ADDITIONS === -->" >> "$temp_file"

        # Add DOT-CLAUDE bootstrap
        if [[ -f "$DOT_CLAUDE_ROOT/CLAUDE.bootstrap.md" ]]; then
            cat "$DOT_CLAUDE_ROOT/CLAUDE.bootstrap.md" >> "$temp_file"
        elif [[ -f "$DOT_CLAUDE_ROOT/CLAUDE.md" ]]; then
            cat "$DOT_CLAUDE_ROOT/CLAUDE.md" >> "$temp_file"
        fi

        mv "$temp_file" "$claude_md"
    else
        # Fresh install
        if [[ "$MINIMAL_MODE" == "true" ]]; then
            if [[ -f "$DOT_CLAUDE_ROOT/CLAUDE.bootstrap.md" ]]; then
                cp "$DOT_CLAUDE_ROOT/CLAUDE.bootstrap.md" "$claude_md"
            fi
        else
            if [[ -f "$DOT_CLAUDE_ROOT/CLAUDE.md" ]]; then
                cp "$DOT_CLAUDE_ROOT/CLAUDE.md" "$claude_md"
            fi
        fi
    fi
}

install_agents() {
    local target="$1"

    echo -e "${CYAN}Installing agent personality modules...${NC}"

    # Create agents directory structure
    mkdir -p "$target/agents/managers"
    mkdir -p "$target/agents/ics"
    mkdir -p "$target/agents/personalities"
    mkdir -p "$target/agents/industry"

    # Copy agent modules if they exist
    if [[ -d "$DOT_CLAUDE_ROOT/agents" ]]; then
        rsync -av "$DOT_CLAUDE_ROOT/agents/" "$target/agents/"
    fi

    echo -e "${GREEN}✓ Agent modules installed${NC}"
}

do_install() {
    local target="$1"

    echo -e "${GREEN}Installing DOT-CLAUDE to: $target${NC}"
    echo ""

    # Create target directory
    mkdir -p "$target"

    # Backup if requested
    if [[ "$BACKUP_MODE" == "true" ]]; then
        backup_directory "$target"
    fi

    # Sync directories
    for dir in "${SYNC_DIRS[@]}"; do
        sync_directory "$DOT_CLAUDE_ROOT/$dir" "$target/$dir" "$MERGE_MODE"
    done

    # Sync files
    for file in "${SYNC_FILES[@]}"; do
        sync_file "$DOT_CLAUDE_ROOT/$file" "$target/$file" "$MERGE_MODE"
    done

    # Generate/merge CLAUDE.md
    generate_claude_md "$target" "$INSTALL_MODE"

    # Install agents if requested
    if [[ "$AGENTS_MODE" == "true" ]]; then
        install_agents "$target"
    fi

    # Copy manifest
    if [[ -f "$DOT_CLAUDE_ROOT/manifest.json" ]]; then
        sync_file "$DOT_CLAUDE_ROOT/manifest.json" "$target/manifest.json" "$MERGE_MODE"
    fi

    echo ""
    echo -e "${GREEN}╔═══════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║     Installation Complete!            ║${NC}"
    echo -e "${GREEN}╚═══════════════════════════════════════╝${NC}"
    echo ""
    echo "Installed to: $target"
    echo ""
    echo "Next steps:"
    echo "  1. Review $target/CLAUDE.md"
    echo "  2. Customize settings in $target/settings.json"
    echo "  3. Run 'claude' to start using your new configuration"
}

interactive_mode() {
    print_banner

    echo "Where would you like to install DOT-CLAUDE?"
    echo ""
    echo "  1) Global (~/.claude/) - Available in all projects"
    echo "  2) Project (./.claude/) - Only in current directory"
    echo "  3) Custom path"
    echo "  4) Cancel"
    echo ""
    read -p "Select option [1-4]: " choice

    case $choice in
        1)
            INSTALL_TARGET="$HOME/.claude"
            INSTALL_MODE="global"
            ;;
        2)
            INSTALL_TARGET="./.claude"
            INSTALL_MODE="project"
            ;;
        3)
            read -p "Enter custom path: " custom_path
            INSTALL_TARGET="$custom_path"
            INSTALL_MODE="custom"
            ;;
        *)
            echo "Cancelled."
            exit 0
            ;;
    esac

    echo ""
    echo "Installation options:"
    echo ""
    read -p "Create backup first? [Y/n]: " backup_choice
    [[ ! "$backup_choice" =~ ^[Nn]$ ]] && BACKUP_MODE="true"

    if [[ -d "$INSTALL_TARGET" ]]; then
        read -p "Merge with existing config? [Y/n]: " merge_choice
        [[ ! "$merge_choice" =~ ^[Nn]$ ]] && MERGE_MODE="true"
    fi

    read -p "Install full agent personality system? [y/N]: " agents_choice
    [[ "$agents_choice" =~ ^[Yy]$ ]] && AGENTS_MODE="true"

    read -p "Install minimal bootstrap only? [y/N]: " minimal_choice
    [[ "$minimal_choice" =~ ^[Yy]$ ]] && MINIMAL_MODE="true"

    echo ""
    do_install "$INSTALL_TARGET"
}

# Parse arguments
INSTALL_TARGET=""
INSTALL_MODE=""
BACKUP_MODE="false"
MERGE_MODE="false"
DRY_RUN="false"
FORCE_MODE="false"
AGENTS_MODE="false"
MINIMAL_MODE="false"

while [[ $# -gt 0 ]]; do
    case $1 in
        --global)
            INSTALL_TARGET="$HOME/.claude"
            INSTALL_MODE="global"
            shift
            ;;
        --project)
            INSTALL_TARGET="./.claude"
            INSTALL_MODE="project"
            shift
            ;;
        --merge)
            MERGE_MODE="true"
            shift
            ;;
        --backup)
            BACKUP_MODE="true"
            shift
            ;;
        --dry-run)
            DRY_RUN="true"
            shift
            ;;
        --force)
            FORCE_MODE="true"
            shift
            ;;
        --agents)
            AGENTS_MODE="true"
            shift
            ;;
        --minimal)
            MINIMAL_MODE="true"
            shift
            ;;
        --help|-h)
            print_help
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            print_help
            exit 1
            ;;
    esac
done

# Run installation
if [[ -z "$INSTALL_TARGET" ]]; then
    interactive_mode
else
    print_banner
    do_install "$INSTALL_TARGET"
fi
